import Foundation

extension ToolHelp {
    static let professionalHelp: [String: ToolHelpContent] = [
        "ssh": ToolHelpContent(
            overview: LocalizedText(en: "A from-scratch SSH-2 client built into the app: run one command on a remote server or open an interactive line shell. Supports password or private-key auth (ed25519, ECDSA, or RSA) and shows the host key fingerprint. Built entirely on CryptoKit with no external library.", ar: "عميل SSH-2 كامل مبني من الصفر داخل التطبيق: يشغّل أمرًا واحدًا على خادم بعيد أو يفتح صدفة سطرية تفاعلية. يدعم المصادقة بكلمة مرور أو مفتاح خاص (ed25519 أو ECDSA أو RSA) ويعرض بصمة مفتاح المضيف. يعتمد كليًا على CryptoKit بلا مكتبات خارجية."),
            howItWorks: LocalizedText(en: "It connects over TCP to port 22 by default, then does a real SSH-2 handshake: curve25519-sha256 key exchange and aes256-gcm encryption, with the host key signature verified. Auth uses a password or a publickey request (ed25519, ECDSA nistp256/384/521, or RSA). Command mode opens a session channel and sends exec; shell mode requests a pty then a shell.", ar: "يتصل عبر TCP بالمنفذ 22 افتراضيًا ثم يجري مصافحة SSH-2 حقيقية: تبادل مفاتيح curve25519-sha256 وتشفير aes256-gcm مع التحقق من توقيع مفتاح المضيف. تجري المصادقة بطلب password أو publickey (ed25519 أو ECDSA nistp256/384/521 أو RSA). وضع الأمر يفتح قناة session ويرسل exec؛ ووضع الصدفة يطلب pty ثم shell."),
            example: LocalizedText(en: "Host test.rebex.net, port 22, user demo, password 'password', mode command, command 'uname -a'. Expected: host key type ssh-ed25519 with a SHA256 fingerprint, then an output line describing the server OS and exit status 0.", ar: "المضيف test.rebex.net، المنفذ 22، المستخدم demo، كلمة المرور 'password'، الوضع command، الأمر 'uname -a'. المتوقّع: نوع مفتاح المضيف ssh-ed25519 مع بصمة SHA256، ثم سطر مخرجات يصف نظام الخادم ورمز خروج 0."),
            notes: LocalizedText(en: "Only curve25519-sha256 exchange and AES-GCM are supported; other servers are rejected. Key auth supports ed25519, ECDSA (nistp256/384/521) and RSA (RSA keys must be in PEM form). The app remembers each host's key on first use and warns if it later changes (trust-on-first-use). Command output is capped near 4 MB.", ar: "يُدعم فقط تبادل curve25519-sha256 وتشفير AES-GCM؛ وتُرفَض الخوادم الأخرى. تدعم مصادقة المفتاح ed25519 وECDSA (nistp256/384/521) وRSA (مفاتيح RSA بصيغة PEM). يتذكّر التطبيق مفتاح كل مضيف عند أول اتصال وينبّه إذا تغيّر لاحقًا (الثقة عند أول استخدام). مخرجات الأمر محدودة بنحو 4 ميغابايت.")
        ),
        "telnet": ToolHelpContent(
            overview: LocalizedText(en: "A simple Telnet client that opens a live plaintext session with a remote server on port 23 by default. Useful for testing text services, reading welcome banners, and interacting with legacy or network gear. Native over the Network framework with no external libraries.", ar: "عميل Telnet بسيط يفتح جلسة نصّية حيّة مع خادم بعيد على المنفذ 23 افتراضيًا. مفيد لاختبار الخدمات النصّية وقراءة لافتات الترحيب والتفاعل مع المعدّات القديمة أو أجهزة الشبكة. أصلي عبر إطار Network بلا مكتبات خارجية."),
            howItWorks: LocalizedText(en: "It opens a plain unencrypted TCP connection to port 23 (RFC 854). Incoming data is split into displayable text and IAC option-negotiation commands; the client negotiates the useful options — it advertises a terminal type (xterm) and window size (80×24), suppresses go-ahead, and lets the server echo — and politely refuses the rest. Output is rendered through a VT100 emulator so colours and cursor moves display correctly. Typed commands are sent with a CR-LF ending.", ar: "يفتح اتصال TCP عاديًا غير مشفّر بالمنفذ 23 (RFC 854). البيانات الواردة تُفصَل إلى نص قابل للعرض وأوامر تفاوض IAC؛ يتفاوض العميل على الخيارات المفيدة — يعلن نوع طرفية (xterm) وحجم نافذة (80×24)، ويكبت go-ahead، ويسمح للخادم بالصدى — ويرفض الباقي بأدب. وتُعرَض المخرجات عبر محاكي VT100 لتظهر الألوان وحركات المؤشّر بشكل صحيح. الأوامر المُدخَلة تُرسَل بنهاية سطر CR-LF."),
            example: LocalizedText(en: "Host telehack.com, port 23. After connecting a text welcome banner appears; type 'help' and send to see the list of available commands appear in the terminal pane.", ar: "المضيف telehack.com، المنفذ 23. بعد الاتصال تظهر لافتة ترحيب نصّية؛ اكتب 'help' وأرسِل لترى قائمة الأوامر المتاحة في نافذة الطرفية."),
            notes: LocalizedText(en: "Telnet is entirely unencrypted plaintext — everything, including any passwords, is sent in the clear; use SSH for sensitive systems. The client negotiates terminal type/size and accepts server echo, and renders output through a VT100 emulator; full-screen apps like vi/top aren't fully supported.", ar: "Telnet نصّي غير مشفّر بالكامل — كل شيء بما فيه كلمات المرور يُرسَل بوضوح؛ استخدم SSH للأنظمة الحسّاسة. يتفاوض العميل على نوع الطرفية وحجمها ويقبل صدى الخادم، ويعرض المخرجات عبر محاكي VT100؛ التطبيقات ملء الشاشة مثل vi/top غير مدعومة بالكامل.")
        ),
        "mikrotik-api": ToolHelpContent(
            overview: LocalizedText(en: "A live terminal that connects to MikroTik routers over the RouterOS API on TCP port 8728. It lets you log in and run RouterOS commands such as /system/resource/print, showing replies as structured key:value records.", ar: "طرفية حيّة تتصل بموجّهات MikroTik عبر واجهة RouterOS API على منفذ TCP رقم 8728. تتيح تسجيل الدخول وتنفيذ أوامر RouterOS مثل /system/resource/print وعرض الردود كسجلات منظَّمة بحقول مفتاح:قيمة."),
            howItWorks: LocalizedText(en: "It opens a TCP connection to host:8728 (8-second timeout) then does plain login (RouterOS 6.43+) with the sentence /login. The API protocol uses length-prefixed «words» grouped into «sentences»; commands are split on spaces and replies read until a done or fatal sentence, with each record shown numbered.", ar: "يفتح اتصال TCP إلى host:8728 (مهلة 8 ثوانٍ) ثم يسجّل الدخول العادي (RouterOS 6.43 فأحدث) بجملة login. يعتمد البروتوكول على «كلمات» مؤطّرة بطول تُجمَّع في «جُمَل»؛ تُقسَّم الأوامر على المسافات وتُقرأ الردود حتى تصل جملة done أو fatal، ويظهر كل سجل مرقَّمًا."),
            example: LocalizedText(en: "Connect to 192.168.88.1:8728 as admin, then run /system/resource/print. Result is one record with fields such as uptime, version 7.15.2, board-name hAP ac2, cpu-load, and free-memory, ending with 'done · 1 records'.", ar: "اتصل بـ 192.168.88.1:8728 بالمستخدم admin ثم شغّل /system/resource/print. النتيجة سجل واحد بحقول مثل uptime وversion 7.15.2 وboard-name hAP ac2 وcpu-load وfree-memory، ينتهي بـ 'done · 1 records'."),
            notes: LocalizedText(en: "Port 8728 is unencrypted, so credentials and commands travel in clear text — use it only on a trusted network, not the open internet (the encrypted API-SSL port 8729 is not supported). Plain login needs RouterOS 6.43 or newer; each operation times out after 8 seconds.", ar: "المنفذ 8728 غير مشفّر، فتُرسَل بيانات الاعتماد والأوامر بنص واضح — استخدمه في شبكة موثوقة فقط لا عبر الإنترنت المكشوف (منفذ API-SSL المشفّر 8729 غير مدعوم). يتطلب تسجيل الدخول العادي RouterOS 6.43 فأحدث؛ ومهلة كل عملية 8 ثوانٍ.")
        ),
        "sftp": ToolHelpContent(
            overview: LocalizedText(en: "Browse and securely download files on a remote server over SFTP (file transfer over SSH). It reuses the same from-scratch SSH-2 client, so everything is encrypted; you can list directories, navigate, and download and share files.", ar: "تصفّح ملفات خادم بعيد وتنزيلها بأمان عبر SFTP (نقل الملفات فوق SSH). تعتمد على نفس عميل SSH-2 المبني من الصفر، فكل ما يمرّ مشفّر؛ يمكنك استعراض المجلّدات والتنقّل وتنزيل الملفات ومشاركتها."),
            howItWorks: LocalizedText(en: "It connects to port 22 by default (SFTP is a subsystem inside SSH). After the SSH-2 handshake (curve25519-sha256 exchange, aes256-gcm encryption) it opens a session channel, requests the sftp subsystem, and runs an SFTP version-3 handshake — listing via OPENDIR/READDIR and downloading via OPEN/READ in 32768-byte chunks.", ar: "يتصل بالمنفذ 22 افتراضيًا (SFTP نظام فرعي داخل SSH). بعد مصافحة SSH-2 (تبادل curve25519-sha256 وتشفير aes256-gcm) يفتح قناة session ويطلب النظام الفرعي sftp ويجري مصافحة SFTP إصدار 3 — الاستعراض عبر OPENDIR/READDIR والتنزيل عبر OPEN/READ بمقاطع 32768 بايت."),
            example: LocalizedText(en: "Host test.rebex.net, port 22, user demo, password 'password', path '.'. Expected: a listing with a pub folder and a file like readme.txt; navigating into pub/example then tapping ReadMe.txt downloads it and offers to share.", ar: "المضيف test.rebex.net، المنفذ 22، المستخدم demo، كلمة المرور 'password'، المسار '.'. المتوقّع: قائمة بها مجلّد pub وملف مثل readme.txt؛ الدخول إلى pub/example ثم النقر على ReadMe.txt ينزّله ويتيح مشاركته."),
            notes: LocalizedText(en: "Each list or download opens a fresh connection; downloads are capped near 8 MB per file. It inherits SSH limits: curve25519-sha256 exchange, AES-GCM, ed25519 auth only, and SFTP version 3. Though encrypted, downloaded files are stored temporarily on the device.", ar: "كل استعراض أو تنزيل يفتح اتصالًا جديدًا؛ والتنزيل محدود بنحو 8 ميغابايت لكل ملف. يرث قيود SSH: تبادل curve25519-sha256 وAES-GCM ومصادقة ed25519 فقط وإصدار SFTP رقم 3. ورغم التشفير تُخزَّن الملفات المنزّلة مؤقتًا على الجهاز.")
        ),
        "ftp": ToolHelpContent(
            overview: LocalizedText(en: "A simple FTP tool that connects, logs in, and lists a directory over passive mode. Useful for probing FTP servers, confirming credentials, and reading listings. Plaintext FTP only — for encrypted transfer use SFTP, which is built on SSH.", ar: "أداة FTP بسيطة تتصل وتسجّل الدخول وتستعرض مجلّدًا عبر الوضع السلبي. مفيدة لفحص خوادم FTP والتأكد من بيانات الدخول وقراءة القوائم. FTP نصّي فقط — وللنقل المشفّر استخدم SFTP المبني على SSH."),
            howItWorks: LocalizedText(en: "It opens a control connection on port 21, reads the 220 greeting, then sends USER, PASS, TYPE A, and PASV. The 227 passive response is parsed for the data host and port (port = p1×256 + p2), a second data connection is opened, LIST is sent, and the listing is read.", ar: "يفتح قناة تحكّم على المنفذ 21 ويقرأ لافتة 220 ثم يرسل USER وPASS وTYPE A وPASV. تُحلَّل استجابة الوضع السلبي 227 لاستخراج مضيف ومنفذ البيانات (المنفذ = p1×256 + p2)، ويُفتح اتصال بيانات ثانٍ، ويُرسَل LIST وتُقرأ القائمة."),
            example: LocalizedText(en: "Host ftp.gnu.org, port 21, user anonymous, password 'anonymous@', path /gnu. Expected: a listing of ls-l style lines like 'drwxr-xr-x 2 ftp ftp 4096 Jan 01 2024 bash' showing folders and files under /gnu.", ar: "المضيف ftp.gnu.org، المنفذ 21، المستخدم anonymous، كلمة المرور 'anonymous@'، المسار /gnu. المتوقّع: قائمة بأسطر بأسلوب ls-l مثل 'drwxr-xr-x 2 ftp ftp 4096 Jan 01 2024 bash' تعرض المجلّدات والملفات تحت /gnu."),
            notes: LocalizedText(en: "FTP is plaintext and unencrypted — the username, password, and all data travel in the clear; prefer SFTP with sensitive credentials. It supports passive mode only and is limited to directory listing (no per-file upload or download); each stage times out after 8 seconds.", ar: "FTP نصّي غير مشفّر — اسم المستخدم وكلمة المرور وكل البيانات تُرسَل بوضوح؛ فضّل SFTP مع البيانات الحسّاسة. يدعم الوضع السلبي فقط ويقتصر على استعراض القوائم (لا رفع أو تنزيل ملفات فردية)؛ ومهلة كل مرحلة 8 ثوانٍ.")
        ),
        "tftp": ToolHelpContent(
            overview: LocalizedText(en: "A read client for TFTP (RFC 1350) that downloads a file from a TFTP server over UDP port 69. It shows the size and a text preview of the file start, and saves the full file to Documents with a Share option.", ar: "عميل قراءة لبروتوكول TFTP (RFC 1350) يُنزّل ملفًا من خادم TFTP عبر منفذ UDP رقم 69. يعرض الحجم ومعاينة نصية لأول الملف، ويحفظ الملف كاملًا في المستندات مع خيار مشاركة."),
            howItWorks: LocalizedText(en: "It sends a Read Request (RRQ, opcode 1) with the filename and octet mode. Because TFTP replies from a new source port (the Transfer ID), it uses a raw unconnected UDP socket and ACKs each block back to the address it arrived from. Blocks are 512 bytes; a shorter block marks end-of-file.", ar: "يرسل رزمة طلب قراءة (RRQ، رمز 1) باسم الملف ووضع octet الثنائي. ولأن TFTP يردّ من منفذ مصدر جديد (معرّف النقل)، يستخدم مقبس UDP خام غير متصل ويؤكّد ACK كل كتلة إلى العنوان الذي وردت منه. كل كتلة 512 بايت؛ والكتلة الأقصر تعني نهاية الملف."),
            example: LocalizedText(en: "Host 192.168.88.1, port 69, filename config.rsc. Result: 'downloaded · 2048 bytes' with a preview showing the start of the config file, plus a Share button.", ar: "المضيف 192.168.88.1، المنفذ 69، اسم الملف config.rsc. النتيجة: 'downloaded · 2048 bytes' مع معاينة تعرض بداية ملف الإعداد، وزر مشاركة."),
            notes: LocalizedText(en: "It supports reads (RRQ) only, not writes, and no RFC 2347 options such as blksize or tsize. TFTP has no authentication; the download cap is two million bytes, and an ERROR packet (opcode 5) shows its message. UDP does not guarantee delivery.", ar: "يدعم القراءة (RRQ) فقط دون الكتابة، ولا خيارات RFC 2347 مثل blksize أو tsize. لا مصادقة في TFTP؛ والحدّ الأقصى مليونا بايت، وإن ورد رمز خطأ (رمز 5) تُعرَض رسالته. وUDP لا يضمن الوصول.")
        ),
        "websocket": ToolHelpContent(
            overview: LocalizedText(en: "A tool for testing WebSocket servers: open a live bidirectional connection, send text messages, and see everything the server sends as it arrives. Useful for trying ws/wss endpoints, echo servers, and real-time apps. Built on the native URLSessionWebSocketTask.", ar: "أداة لاختبار خوادم WebSocket: تفتح اتصالًا حيًّا ثنائي الاتجاه وترسل رسائل نصّية وتعرض كل ما يصل من الخادم فورًا. مفيدة لتجربة نقاط ws/wss وخوادم الصدى وتطبيقات الوقت الحقيقي. مبنية على URLSessionWebSocketTask الأصلي."),
            howItWorks: LocalizedText(en: "It accepts a ws:// (unencrypted) or wss:// (TLS) URL; the port is derived from the scheme (default 80 for ws, 443 for wss). An ephemeral URLSession task handles the HTTP-to-WebSocket upgrade, then a continuous receive loop reports text, binary, close, and error events; text is sent via send(.string).", ar: "تقبل عنوان ws:// (غير مشفّر) أو wss:// (عبر TLS)؛ ويُشتق المنفذ من المخطّط (افتراضيًا 80 لـ ws و443 لـ wss). تتولّى مهمّة URLSession عابرة ترقية HTTP إلى WebSocket، ثم تُبلّغ حلقة استقبال مستمرّة عن الرسائل النصّية والثنائية وأحداث الإغلاق والأخطاء؛ ويُرسَل النص عبر send(.string)."),
            example: LocalizedText(en: "URL wss://echo.websocket.events, then send 'hello'. Expected: a «connected» system message, a sent entry 'hello', then a received entry 'hello' since it is an echo server that returns what it receives.", ar: "العنوان wss://echo.websocket.events ثم إرسال 'hello'. المتوقّع: رسالة نظام «متّصل»، ثم مُدخَلة مُرسَلة 'hello'، ثم واردة 'hello' لأنه خادم صدى يعيد ما يستقبله."),
            notes: LocalizedText(en: "Always use wss:// on public networks since ws:// is unencrypted and exposes messages. The tool sends text only (no binary frame composing) and shows inbound binary as a byte count. The session is ephemeral (no cookies or cache) and the log is capped at 300 entries.", ar: "استخدم wss:// دائمًا على الشبكات العامة لأن ws:// غير مشفّر ويكشف الرسائل. ترسل الأداة نصًّا فقط (لا تأليف إطارات ثنائية) وتعرض الواردة الثنائية كعدّ بايتات. الجلسة عابرة (بلا كوكيز أو ذاكرة مؤقتة) والسجلّ محدود بـ 300 مُدخَلة.")
        ),
        "mqtt": ToolHelpContent(
            overview: LocalizedText(en: "A native MQTT client that connects to a broker, subscribes to topics, publishes messages, and shows incoming messages live. Useful for testing IoT devices, brokers, and message routing. Supports MQTT 3.1.1 at QoS 0 on the Network framework.", ar: "عميل MQTT أصلي يتصل بوسيط ويشترك في المواضيع وينشر الرسائل ويعرض الواردة حيّا. مفيد لاختبار أجهزة إنترنت الأشياء والوسطاء ومسارات الرسائل. يدعم MQTT 3.1.1 بجودة QoS 0 على إطار Network."),
            howItWorks: LocalizedText(en: "It opens TCP (or TLS if enabled) to the broker, port 1883 by default for plain (8883 is conventional for MQTT over TLS). It sends a CONNECT (protocol level 4, clean session, 60-second keep-alive), and on CONNACK code 0 starts a PINGREQ timer; SUBSCRIBE and PUBLISH run at QoS 0 with varint-encoded lengths.", ar: "يفتح TCP (أو TLS إن فُعّل) إلى الوسيط، المنفذ 1883 افتراضيًا للاتصال العادي (و8883 هو المعتاد لـ MQTT عبر TLS). يرسل CONNECT (مستوى البروتوكول 4، جلسة نظيفة، إبقاء 60 ثانية)، وعند CONNACK برمز 0 يبدأ مؤقّت PINGREQ؛ ويجري SUBSCRIBE وPUBLISH بجودة QoS 0 بأطوال مُرمَّزة varint."),
            example: LocalizedText(en: "Host test.mosquitto.org, port 1883, no TLS. Subscribe to nettoolbox/test then publish 'hello' to it. Expected: «connected», then SUB nettoolbox/test, PUB nettoolbox/test → hello, then an incoming nettoolbox/test ▸ hello.", ar: "المضيف test.mosquitto.org، المنفذ 1883، بلا TLS. اشترك في nettoolbox/test ثم انشر 'hello' عليه. المتوقّع: «متّصل» ثم SUB nettoolbox/test ثم PUB nettoolbox/test → hello ثم واردة nettoolbox/test ▸ hello."),
            notes: LocalizedText(en: "QoS 0 only (fire-and-forget, messages may be lost); no retained, will, or advanced publish patterns. Without TLS, credentials and messages travel in the clear — enable TLS for public or sensitive brokers. Packets larger than 1 MB are refused; keep-alive is 60 seconds.", ar: "QoS 0 فقط (تسليم بلا تأكيد، قد تُفقَد الرسائل)؛ ولا رسائل محتجَزة أو وصية أو أنماط نشر متقدّمة. بدون TLS تُرسَل بيانات الاعتماد والرسائل بوضوح — فعّل TLS للوسطاء العامة أو الحسّاسة. الحزم الأكبر من 1 ميغابايت تُرفَض؛ والإبقاء 60 ثانية.")
        ),
        "smtp": ToolHelpContent(
            overview: LocalizedText(en: "A tool that probes an SMTP mail server with a short EHLO handshake, showing the greeting banner and advertised capabilities. A quick health check revealing features like STARTTLS, AUTH, and message size. Fully native with no external libraries.", ar: "أداة تفحص خادم بريد SMTP بمصافحة EHLO قصيرة، فتعرض لافتة الترحيب والقدرات المُعلَنة. فحص سريع للصحّة يكشف ميزات مثل STARTTLS وAUTH وحجم الرسائل. أصلية بالكامل بلا مكتبات خارجية."),
            howItWorks: LocalizedText(en: "It opens TCP (or direct TLS if enabled) to port 25 by default (587 is submission with STARTTLS, 465 is SMTPS over direct TLS). It reads the 220 greeting, sends EHLO, reads the 250 capability lines, then QUIT and the 221 goodbye — logging the whole dialogue with C: and S: prefixes.", ar: "يفتح TCP (أو TLS مباشر إن فُعّل) إلى المنفذ 25 افتراضيًا (و587 للإرسال مع STARTTLS، و465 هو SMTPS عبر TLS مباشر). يقرأ لافتة 220 ويرسل EHLO ويقرأ أسطر القدرات 250 ثم QUIT والوداع 221 — مُسجّلًا الحوار كاملًا ببادئتي C: وS:."),
            example: LocalizedText(en: "Host smtp.gmail.com, port 25, no TLS. Expected transcript: S: 220 greeting, C: EHLO nettoolbox.local, then S: 250 lines for SIZE, STARTTLS, and SMTPUTF8, then C: QUIT and S: 221 closing.", ar: "المضيف smtp.gmail.com، المنفذ 25، بلا TLS. النص المتوقّع: S: 220 ترحيب، ثم C: EHLO nettoolbox.local، ثم أسطر S: 250 لـ SIZE وSTARTTLS وSMTPUTF8، ثم C: QUIT وS: 221 إغلاق."),
            notes: LocalizedText(en: "It is a probe only — it does EHLO then quits, sending no mail and not exercising STARTTLS or AUTH. On port 25 without TLS the dialogue is plaintext. The TLS toggle starts direct TLS (no STARTTLS upgrade), suiting port 465, not 587; connect timeout is 6 seconds.", ar: "الأداة فاحص فقط — تُجري EHLO ثم تنهي، بلا إرسال بريد ولا تجربة STARTTLS أو AUTH. على المنفذ 25 بلا TLS يكون الحوار نصّيًا. مفتاح TLS يبدأ تشفيرًا مباشرًا (لا ترقية STARTTLS)، فيناسب المنفذ 465 لا 587؛ ومهلة الاتصال 6 ثوانٍ.")
        ),
        "redis": ToolHelpContent(
            overview: LocalizedText(en: "A tool that connects to a Redis server, sends one command, and displays the reply formatted. Useful for probing servers, verifying connectivity and auth, and reading values quickly. It parses the RESP protocol and formats its types. Fully native.", ar: "أداة تتصل بخادم Redis وترسل أمرًا واحدًا وتعرض الردّ منسّقًا. مفيدة لفحص الخوادم والتحقق من الاتصال والمصادقة وقراءة القيم بسرعة. تفهم بروتوكول RESP وتنسّق أنواعه. أصلية بالكامل."),
            howItWorks: LocalizedText(en: "It opens TCP (or TLS if enabled) to port 6379 by default. If a password is set it first sends AUTH, then your command text as-is followed by CR-LF (inline form). The reply is parsed per RESP — simple strings, errors, integers, bulk strings, and nested arrays (up to depth 32) — and indented to reflect structure.", ar: "يفتح TCP (أو TLS إن فُعّل) إلى المنفذ 6379 افتراضيًا. إن أُدخِلت كلمة مرور يرسل AUTH أولًا، ثم أمرك النصّي كما هو متبوعًا بـ CR-LF (الصيغة المضمَّنة). يُحلَّل الردّ وفق RESP — سلاسل بسيطة وأخطاء وأعداد صحيحة وسلاسل كتلية ومصفوفات متداخلة (حتى عمق 32) — ويُزاح ليعكس البنية."),
            example: LocalizedText(en: "Host 127.0.0.1, port 6379, command 'INFO server'. Expected: a text block of server info like redis_version:7.2.4 and os:Linux. Or the command 'PING' which returns PONG directly.", ar: "المضيف 127.0.0.1، المنفذ 6379، الأمر 'INFO server'. المتوقّع: كتلة نصّية بمعلومات الخادم مثل redis_version:7.2.4 وos:Linux. أو الأمر 'PING' الذي يعيد PONG مباشرة."),
            notes: LocalizedText(en: "It sends one command per run then closes (no persistent session). Without TLS the command and password travel in the clear — enable TLS for remote or sensitive servers. It uses inline command form, not RESP arrays, so complex spacing or binary bytes may not work; read timeout is 3 seconds.", ar: "ترسل أمرًا واحدًا لكل تشغيل ثم تغلق (لا جلسة مستمرّة). بدون TLS يُرسَل الأمر وكلمة المرور بوضوح — فعّل TLS للخوادم البعيدة أو الحسّاسة. تستخدم الصيغة المضمَّنة لا مصفوفات RESP، فقد لا تعمل مع مسافات معقّدة أو بايتات ثنائية؛ ومهلة القراءة 3 ثوانٍ.")
        ),
        "memcached": ToolHelpContent(
            overview: LocalizedText(en: "Connects to a Memcached server over its plain-text protocol on TCP port 11211 and queries its version and runtime stats. It shows raw server output with no authentication, useful for inspecting cache health, hit rate, and connection counts.", ar: "تتصل بخادم Memcached عبر بروتوكوله النصي على منفذ TCP رقم 11211 وتستعلم عن إصداره وإحصاءاته. تعرض مخرجات الخادم الخام بلا مصادقة، وهي مفيدة لفحص صحّة الذاكرة المؤقتة ومعدل الإصابة وعدد الاتصالات."),
            howItWorks: LocalizedText(en: "It opens a TCP connection to host:11211 (6-second open timeout), sends two text lines — 'version' then 'stats' — and reads everything the server returns (3-second receive timeout) as raw UTF-8. The text protocol replies with 'STAT name value' lines terminated by END. There is no auth or encryption on this path.", ar: "تفتح اتصال TCP إلى host:11211 (مهلة فتح 6 ثوانٍ)، وترسل سطرين نصيين — 'version' ثم 'stats' — وتقرأ كل ما يرده الخادم (مهلة استقبال 3 ثوانٍ) كنص UTF-8 خام. البروتوكول النصي يردّ بأسطر 'STAT اسم قيمة' تنتهي بـ END. لا مصادقة ولا تشفير في هذا المسار."),
            example: LocalizedText(en: "Input 10.0.0.5 on port 11211. Expected output: 'VERSION 1.6.21' then STAT lines such as uptime, curr_connections, get_hits, get_misses, and bytes, ending with END.", ar: "الإدخال 10.0.0.5 على المنفذ 11211. المخرجات المتوقعة: 'VERSION 1.6.21' ثم أسطر STAT مثل uptime وcurr_connections وget_hits وget_misses وbytes، تنتهي بـ END."),
            notes: LocalizedText(en: "The text protocol is unauthenticated, so it works only against network-reachable servers, typically a trusted internal network — it does not cover SASL-secured or binary-protocol servers. The response is read once and not auto-refreshed; the connection closes as soon as the read completes.", ar: "البروتوكول النصي بلا مصادقة، فيعمل فقط مع خوادم يمكن الوصول إليها شبكيًا، وغالبًا شبكة داخلية موثوقة — ولا يشمل خوادم SASL أو الثنائية المؤمّنة. تُقرأ الاستجابة مرة واحدة بلا تحديث تلقائي؛ ويُغلق الاتصال فور اكتمال القراءة.")
        ),
        "modbus": ToolHelpContent(
            overview: LocalizedText(en: "A tool that reads registers from an industrial device over Modbus TCP. Useful for probing PLCs, sensors, and SCADA / industrial control systems. It supports reading holding and input registers. Fully native with no external libraries.", ar: "أداة تقرأ سجلّات من جهاز صناعي عبر Modbus TCP. مفيدة لفحص المتحكّمات المنطقية (PLC) وأجهزة الاستشعار وأنظمة التحكّم الصناعي (SCADA). تدعم قراءة سجلّات الاحتفاظ والإدخال. أصلية بالكامل بلا مكتبات خارجية."),
            howItWorks: LocalizedText(en: "It opens TCP to port 502 by default (the standard Modbus TCP port), builds an MBAP header (transaction id, protocol 0, length, unit id) plus a PDU (function code, start address, quantity). Function 3 reads holding registers, function 4 reads input registers; the response decodes to 16-bit big-endian values, or an exception code if the 0x80 bit is set.", ar: "تفتح TCP إلى المنفذ 502 افتراضيًا (المنفذ القياسي لـ Modbus TCP)، وتبني رأس MBAP (معرّف المعاملة، بروتوكول 0، طول، معرّف الوحدة) مع PDU (رمز الدالة، عنوان البدء، الكمّية). الدالة 3 تقرأ سجلّات الاحتفاظ والدالة 4 تقرأ سجلّات الإدخال؛ وتُفكَّك الاستجابة كأعداد 16-بت big-endian، أو رمز استثناء إن ضُبط البت 0x80."),
            example: LocalizedText(en: "Host 192.168.1.50, port 502, unit 1, function Holding (3), address 0, quantity 5. Expected: five rows like '0 → 230 (0x00E6)' and '1 → 1500 (0x05DC)' representing register values such as a voltage and an RPM.", ar: "المضيف 192.168.1.50، المنفذ 502، الوحدة 1، الدالة Holding (3)، العنوان 0، الكمّية 5. المتوقّع: خمسة سطور مثل '0 → 230 (0x00E6)' و'1 → 1500 (0x05DC)' تمثّل قيم السجلّات مثل جهد ومعدّل دوران."),
            notes: LocalizedText(en: "Modbus TCP has no encryption and no authentication whatsoever — any device on the network can read or write, so never expose it to the public internet. The tool is read-only and supports functions 3 and 4 only (no coils or discrete inputs); max quantity is 125 registers per request, timeout 6 seconds.", ar: "Modbus TCP بلا تشفير ولا مصادقة إطلاقًا — أي جهاز على الشبكة يمكنه القراءة والكتابة، فلا تعرّضه للإنترنت العام. الأداة للقراءة فقط وتدعم الدالتين 3 و4 فقط (لا coils أو discrete inputs)؛ والكمّية القصوى 125 سجلًّا لكل طلب، والمهلة 6 ثوانٍ.")
        ),
        "coap": ToolHelpContent(
            overview: LocalizedText(en: "A minimal client for CoAP (RFC 7252), the protocol used by constrained IoT devices. It sends a Confirmable GET request to a resource over UDP port 5683 and displays the response code and text payload.", ar: "عميل مبسّط لبروتوكول CoAP (RFC 7252) المستخدم في أجهزة إنترنت الأشياء المحدودة الموارد. يرسل طلب GET مؤكَّدًا إلى مورد عبر منفذ UDP رقم 5683 ويعرض رمز الاستجابة والحمولة النصية."),
            howItWorks: LocalizedText(en: "It hand-builds a binary CoAP packet: a 4-byte header (version 1, type CON, code 0.01 = GET, random message ID), with the path split on / and each segment encoded as a Uri-Path option. It is sent over UDP (5-second timeout); the reply's second byte becomes the response code (rendered as class.detail like 2.05), and text after the 0xFF marker is the payload.", ar: "يبني رزمة CoAP ثنائية يدويًا: رأس بطول 4 بايت (الإصدار 1، النوع CON، الرمز 0.01 أي GET، ومعرّف رسالة عشوائي)، مع تقسيم المسار على / وترميز كل قطعة كخيار Uri-Path. تُرسَل عبر UDP (مهلة 5 ثوانٍ)؛ والبايت الثاني في الرد هو رمز الاستجابة (بصيغة class.detail مثل 2.05)، والنص بعد الفاصل 0xFF هو الحمولة."),
            example: LocalizedText(en: "Host coap.me, port 5683, path .well-known/core. Expected: code 2.05 with a payload listing resources such as </large>;rt='Text',</time>;if='clock'.", ar: "المضيف coap.me، المنفذ 5683، المسار .well-known/core. المتوقّع: رمز 2.05 وحمولة تسرد الموارد مثل </large>;rt='Text',</time>;if='clock'."),
            notes: LocalizedText(en: "This client supports GET only — no DTLS (secure port 5684), no block-wise transfer for large payloads, and no Observe. The request is Confirmable but there is no automatic retransmission on packet loss; it times out after 5 seconds, and UDP does not guarantee delivery.", ar: "يدعم هذا العميل GET فقط — لا DTLS (المنفذ المؤمّن 5684) ولا Block-wise للحمولات الكبيرة ولا آلية Observe. الطلب مؤكَّد لكن لا إعادة إرسال تلقائية عند فقد الرزمة؛ وينتهي بمهلة 5 ثوانٍ، وUDP لا يضمن الوصول.")
        ),
        "snmp": ToolHelpContent(
            overview: LocalizedText(en: "An SNMP query tool that reads OID values from network devices over UDP port 161. It supports GET for a single value and Walk (via GETNEXT) to traverse a whole subtree using SNMP v2c, plus a beta v3 authNoPriv mode.", ar: "أداة استعلام SNMP تقرأ قيم كائنات الإدارة (OIDs) من الأجهزة الشبكية عبر منفذ UDP رقم 161. تدعم GET لقيمة واحدة وWalk (عبر GETNEXT) لتصفّح شجرة فرعية باستخدام SNMP v2c، إضافةً إلى وضع v3 التجريبي بمستوى authNoPriv."),
            howItWorks: LocalizedText(en: "In v2c mode the SNMP message is BER-encoded and sent over UDP (5-second timeout). GET returns a single varbind (OID, type, value); Walk issues successive GETNEXT requests from the given OID, stopping when it leaves the subtree, capped at 256 steps. The beta v3 mode uses USM at authNoPriv (authentication, no encryption) over GET only.", ar: "في وضع v2c تُرمَّز رسالة SNMP بترميز BER وتُرسَل عبر UDP (مهلة 5 ثوانٍ). عملية GET تعيد varbind واحدًا (OID، نوع، قيمة)؛ وWalk تُصدر طلبات GETNEXT متتالية من الـ OID المُعطى وتتوقف عند مغادرة الشجرة الفرعية، بحدّ 256 خطوة. ووضع v3 التجريبي يستخدم USM بمستوى authNoPriv (مصادقة بلا تشفير) عبر GET فقط."),
            example: LocalizedText(en: "Host 192.168.1.1, community public, OID 1.3.6.1.2.1.1.1.0, mode get. Result: Type OCTET STRING, Value 'MikroTik RouterOS 7.15.2 (hAP ac2)'. A walk on the interfaces subtree lists names like ether1, ether2, wlan1.", ar: "المضيف 192.168.1.1، المجتمع public، الـ OID 1.3.6.1.2.1.1.1.0، الوضع get. النتيجة: النوع OCTET STRING، القيمة 'MikroTik RouterOS 7.15.2 (hAP ac2)'. وWalk على شجرة الواجهات يسرد أسماء مثل ether1 وether2 وwlan1."),
            notes: LocalizedText(en: "v2c sends the community string in clear text with no encryption; use it on a trusted network, and the device must permit SNMP from your address. Walk is limited to 256 steps as a safeguard. The v3 mode is beta and supports authNoPriv and GET only; each request times out after 5 seconds and UDP is not guaranteed.", ar: "v2c ترسل سلسلة المجتمع بنص واضح بلا تشفير؛ استخدمها في شبكة موثوقة، ويجب أن يسمح الجهاز بـ SNMP من عنوانك. وWalk محدود بـ 256 خطوة كحماية. وضع v3 تجريبي ويدعم authNoPriv وGET فقط؛ ومهلة كل طلب 5 ثوانٍ وUDP لا يضمن الوصول.")
        ),
        "snmp-trap": ToolHelpContent(
            overview: LocalizedText(en: "A receiver for SNMP Traps that binds a local UDP port and waits for inbound trap messages from network devices. For each trap it best-effort decodes the version and community and shows a summary with the first 48 bytes in hex. The standard SNMP-trap port is 162.", ar: "مستقبِل لمصائد SNMP يربط منفذ UDP محلياً وينتظر رسائل المصائد الواردة من الأجهزة الشبكية. لكل مصيدة يفكّ ترميز الإصدار واسم المجتمع بأفضل جهد ويعرض ملخصًا مع أول 48 بايت بصيغة ست عشرية. المنفذ القياسي لمصائد SNMP هو 162."),
            howItWorks: LocalizedText(en: "It is a receiver: it binds a local UDP socket and listens until packets arrive — devices must be configured to send traps to your IP and this port. A simple decoder walks the BER encoding to read the version (0=v1, 1=v2c) and community, giving a summary like «SNMP v2c · community: public». The last 200 traps are kept.", ar: "هي أداة مستقبِلة: تربط مقبس UDP محلياً وتُصغي حتى ترد رزم — يجب ضبط الأجهزة لإرسال مصائدها إلى عنوانك وهذا المنفذ. يمشي مفكِّك بسيط عبر ترميز BER ليقرأ الإصدار (0=v1، 1=v2c) والمجتمع، فينتج ملخص مثل «SNMP v2c · community: public». وتُحفظ آخر 200 مصيدة."),
            example: LocalizedText(en: "Start listening on 1162 (the app default, since binding ports below 1024 needs privileges), then point a switch at device-ip:1162. An inbound trap shows summary «SNMP v2c · community: public», sender 192.168.1.10, and a hex line.", ar: "ابدأ الإصغاء على 1162 (افتراضي التطبيق، لأن ربط المنافذ أدنى من 1024 يتطلب صلاحيات)، ثم وجّه سويتشًا إلى device-ip:1162. المصيدة الواردة تظهر بملخص «SNMP v2c · community: public» والمرسِل 192.168.1.10 وسطر ست عشري."),
            notes: LocalizedText(en: "Decoding is best-effort and surfaces only version and community, without parsing trap varbinds or resolving OID names, and it does not support encrypted/authenticated SNMPv3 traps. The tool receives nothing unless devices send to it, a firewall may block packets, and storage is in-memory only (capped at 200).", ar: "فك الترميز أفضل-جهد ويعرض الإصدار والمجتمع فقط دون تفسير متغيّرات المصيدة أو مطابقة أسماء OIDs، ولا يدعم مصائد SNMPv3 المشفّرة أو المصادَق عليها. الأداة لا تستقبل شيئًا ما لم ترسل الأجهزة إليها، وقد يمنع الجدار الناري الرزم، والتخزين في الذاكرة فقط (بحدّ 200).")
        ),
        "syslog": ToolHelpContent(
            overview: LocalizedText(en: "A Syslog receiver that binds a local UDP port and waits for inbound messages from network devices (routers, switches, servers). For each message it extracts the severity from the <PRI> priority prefix and displays the sender and text. The default port is 5140.", ar: "مستقبِل رسائل Syslog يربط منفذ UDP محلياً وينتظر الرسائل الواردة من الأجهزة الشبكية (راوترات، سويتشات، خوادم). لكل رسالة يستخرج الخطورة من بادئة الأولوية <PRI> ويعرض المرسِل والنص. المنفذ الافتراضي 5140."),
            howItWorks: LocalizedText(en: "It is a receiver: it binds a local UDP socket and listens until packets arrive — other devices must be configured to send logs to your IP and this port. Each packet is decoded as UTF-8, and if it starts with a <PRI> prefix, severity is computed as PRI % 8 and matched to the RFC 3164/5424 list (emerg, alert, crit, err, warning, notice, info, debug). The last 300 messages are kept.", ar: "هي أداة مستقبِلة: تربط مقبس UDP محلياً وتُصغي حتى ترد رزم — يجب ضبط الأجهزة لإرسال سجلاتها إلى عنوانك وهذا المنفذ. تُفكّ كل رزمة كـ UTF-8، وإن بدأت ببادئة <PRI> تُحسب الخطورة كـ PRI % 8 وتُطابَق قائمة RFC 3164/5424 (emerg, alert, crit, err, warning, notice, info, debug). وتُحفظ آخر 300 رسالة."),
            example: LocalizedText(en: "Start listening on 5140 (the app default, since binding port 514 needs privileges), then configure a router to send logs to device-ip:5140. A message like '<134>… sshd: Accepted password for admin' appears with severity INFO (134 % 8 = 6).", ar: "ابدأ الإصغاء على 5140 (افتراضي التطبيق، لأن ربط المنفذ 514 يتطلب صلاحيات)، ثم اضبط راوترًا لإرسال السجلات إلى device-ip:5140. رسالة مثل '<134>… sshd: Accepted password for admin' تظهر بخطورة INFO (134 % 8 = 6)."),
            notes: LocalizedText(en: "The tool receives nothing unless devices are configured to send Syslog to it, and a firewall or cellular network may block packets. It does not support Syslog over TCP or TLS (port 6514). Messages live in memory only (capped at 300), and the port cannot be changed while listening.", ar: "الأداة لا تستقبل شيئًا ما لم تُضبط الأجهزة لإرسال Syslog إليها، وقد يمنع الجدار الناري أو شبكة الجوّال الرزم. ولا تدعم Syslog فوق TCP أو TLS (المنفذ 6514). الرسائل في الذاكرة فقط (بحدّ 300)، ولا يمكن تغيير المنفذ أثناء الإصغاء.")
        ),
        "iperf3": ToolHelpContent(
            overview: LocalizedText(en: "A native iperf3 client on Network.framework that measures TCP throughput against an iperf3 -s server. It connects on TCP port 5201 and measures speed in Mbit/s in the download or upload direction, with a live readout during the test.", ar: "عميل iperf3 أصلي على Network.framework يقيس إنتاجية TCP مقابل خادم iperf3 -s. يتصل على منفذ TCP رقم 5201 ويقيس السرعة بالميغابت/ثانية في اتجاه التنزيل أو الرفع، مع عرض حيّ أثناء الاختبار."),
            howItWorks: LocalizedText(en: "It performs the full iperf3 control handshake over TCP: a 37-byte cookie, then PARAM_EXCHANGE (test JSON), CREATE_STREAMS, TEST_START/RUNNING/END, and EXCHANGE_RESULTS. In download (reverse) mode the server sends and the client counts inbound bytes; in upload mode the client blasts data. Throughput is computed locally, updated about twice per second.", ar: "ينفّذ مصافحة تحكّم iperf3 الكاملة عبر TCP: cookie بطول 37 بايت، ثم PARAM_EXCHANGE (معطيات JSON) وCREATE_STREAMS وTEST_START/RUNNING/END وEXCHANGE_RESULTS. في وضع التنزيل (reverse) يرسل الخادم والعميل يعدّ البايتات الواردة؛ وفي وضع الرفع يبثّ العميل البيانات. تُحسب السرعة محلياً وتُحدَّث نحو مرتين في الثانية."),
            example: LocalizedText(en: "Host iperf.he.net, port 5201, direction download, duration 10, one stream. Typical result: a live readout around 93.4 Mbit/s, and on completion transferred ≈ 111 MiB, duration 10.0 s, direction download.", ar: "المضيف iperf.he.net، المنفذ 5201، الاتجاه download، المدة 10، تدفّق واحد. النتيجة النموذجية: قراءة حيّة حول 93.4 Mbit/s، وعند الانتهاء transferred ≈ 111 MiB، duration 10.0 s، direction download."),
            notes: LocalizedText(en: "It supports TCP only (no UDP), has no authentication (--rsa unsupported), and targets a plain iperf3 -s server; if the server is running another test it refuses. Speed is from the local byte counter, not the server. Duration is clamped to 1–60 seconds and parallelism to 1–16 streams, and results depend on link quality.", ar: "يدعم TCP فقط (لا UDP)، وبلا مصادقة (‏--rsa غير مدعوم)، ويستهدف خادم iperf3 -s عاديًا؛ وإن كان يشغّل اختبارًا آخر يرفض الاتصال. السرعة من عدّاد البايتات المحلي لا من الخادم. المدة مقيّدة بـ 1–60 ثانية والتوازي بـ 1–16 تدفّقًا، والنتائج تتأثر بجودة الاتصال.")
        )
    ]

    static let bgpHelp: [String: ToolHelpContent] = [
        "bgp-asn": ToolHelpContent(
            overview: LocalizedText(en: "Looks up an Autonomous System Number in the global BGP table, showing the holder name, type, neighbour count, and announced prefixes. It uses the public RIPEstat data API at stat.ripe.net, no key required.", ar: "أداة تستعلم عن رقم نظام ذاتي (ASN) في جدول BGP العالمي، فتُظهر اسم المالك والنوع وعدد الجيران والبادئات المُعلَنة. تعتمد على واجهة بيانات RIPEstat العامة على stat.ripe.net بلا مفتاح."),
            howItWorks: LocalizedText(en: "It normalizes the input to a number (accepts AS15169, as15169, or 15169), then calls three RIPEstat endpoints at stat.ripe.net over HTTPS: as-overview (holder and type), announced-prefixes (the prefix list), and asn-neighbours (counted). The JSON responses are merged into one result.", ar: "تُطبّع المُدخَل إلى رقم (تقبل AS15169 أو as15169 أو 15169)، ثم تستدعي ثلاث نقاط من RIPEstat على stat.ripe.net عبر HTTPS: as-overview (المالك والنوع)، وannounced-prefixes (قائمة البادئات)، وasn-neighbours (يُحسب عددها). وتُجمَّع ردود JSON في نتيجة واحدة."),
            example: LocalizedText(en: "Input AS15169 (Google). Result: ASN 15169, Holder GOOGLE, Type content, Neighbours 200+, and a prefix list including 8.8.8.0/24, 8.8.4.0/24, and 142.250.0.0/15.", ar: "الإدخال AS15169 (Google). النتيجة: ASN 15169، المالك GOOGLE، النوع content، الجيران 200+، وقائمة بادئات تتضمن 8.8.8.0/24 و8.8.4.0/24 و142.250.0.0/15."),
            notes: LocalizedText(en: "Requires internet access to reach stat.ripe.net. Data comes from RIPEstat and reflects what RIPE's collectors observe of global routing (there may be slight delay or divergence). Queries carry the sourceapp=nettoolbox tag, and only the first 200 prefixes are shown in the UI.", ar: "تتطلب اتصال إنترنت للوصول إلى stat.ripe.net. البيانات من RIPEstat وتعكس ما ترصده مجمّعات RIPE من التوجيه العالمي (قد يوجد تأخّر أو تفاوت طفيف). تُرسَل الاستعلامات مع الوسم sourceapp=nettoolbox، وتُعرض أول 200 بادئة فقط في الواجهة.")
        ),
        "bgp-ip": ToolHelpContent(
            overview: LocalizedText(en: "Resolves an IP address (or prefix) to the covering prefix in the global routing table and to the origin AS(es) announcing it. It uses the public RIPEstat data API at stat.ripe.net, no key required.", ar: "أداة تُحوِّل عنوان IP (أو بادئة) إلى البادئة المغطّية في التوجيه العالمي وإلى نظام/أنظمة المصدر (Origin AS) التي تُعلن عنه. تعتمد على واجهة بيانات RIPEstat العامة على stat.ripe.net بلا مفتاح."),
            howItWorks: LocalizedText(en: "It calls RIPEstat's network-info endpoint at stat.ripe.net over HTTPS to get the covering prefix and AS numbers, then calls prefix-overview to fetch AS numbers with holder names. If prefix-overview returns nothing, the network-info AS numbers are used as a fallback (without holder names).", ar: "تستدعي نقطة network-info من RIPEstat على stat.ripe.net عبر HTTPS للحصول على البادئة المغطّية وأرقام الأنظمة، ثم تستدعي prefix-overview لجلب أرقام الأنظمة مع أسماء المالكين. وإن لم تُرجِع prefix-overview نتائج تُستخدَم أنظمة network-info كبديل (بلا أسماء)."),
            example: LocalizedText(en: "Input 8.8.8.8. Result: Query 8.8.8.8, Prefix 8.8.8.0/24, and origin AS15169 — GOOGLE.", ar: "الإدخال 8.8.8.8. النتيجة: الاستعلام 8.8.8.8، البادئة 8.8.8.0/24، والمصدر AS15169 — GOOGLE."),
            notes: LocalizedText(en: "Requires internet access to reach stat.ripe.net. Data comes from RIPEstat and reflects RIPE's collector view of global routing. A prefix may be announced by more than one origin AS (multi-origin). Queries carry the sourceapp=nettoolbox tag, and it works with IPv4, IPv6, and prefixes.", ar: "تتطلب اتصال إنترنت للوصول إلى stat.ripe.net. البيانات من RIPEstat وتعكس رصد مجمّعات RIPE للتوجيه العالمي. وقد يُعلن عن البادئة أكثر من نظام مصدر واحد (multi-origin). تُرسَل الاستعلامات مع الوسم sourceapp=nettoolbox، وتعمل مع IPv4 وIPv6 والبادئات."),
        ),
        "rpki": ToolHelpContent(
            overview: LocalizedText(en: "Validates a BGP route announcement against RPKI. Given an AS number and a prefix, it shows whether the pair is valid, invalid, or unknown, along with the matching Route Origin Authorizations (ROAs). It uses the RIPEstat data API at stat.ripe.net.", ar: "أداة تتحقق من صلاحية إعلان مسار BGP وفق RPKI. بإدخال رقم نظام ذاتي وبادئة، تُظهر ما إذا كان الزوج صالحًا أو غير صالح أو غير معروف، مع شهادات أصل المسار (ROAs) المطابِقة. تعتمد على واجهة بيانات RIPEstat على stat.ripe.net."),
            howItWorks: LocalizedText(en: "It normalizes the ASN to digits (accepts AS13335, as 13335, or 13335), then requests the rpki-validation endpoint at stat.ripe.net over HTTPS with an ephemeral non-caching session. The status field is normalized (valid; invalid/invalid_asn/invalid_length → invalid; else unknown), and the validating_roas array shows each ROA's origin, prefix, max-length, and validity.", ar: "تُطبّع الـ ASN إلى أرقام (تقبل AS13335 أو as 13335 أو 13335)، ثم تطلب نقطة rpki-validation من stat.ripe.net عبر HTTPS بجلسة عابرة بلا تخزين مؤقت. يُطبَّع حقل status (صالح؛ وinvalid/invalid_asn/invalid_length → غير صالح؛ وغير ذلك → غير معروف)، وتعرض مصفوفة validating_roas لكل شهادة أصلها وبادئتها وطولها الأقصى وصلاحيتها."),
            example: LocalizedText(en: "Input ASN AS13335, prefix 1.1.1.0/24. Result: a green valid badge, with a ROA AS13335 → 1.1.1.0/24, max-length /24 · valid.", ar: "الإدخال ASN AS13335، البادئة 1.1.1.0/24. النتيجة: شارة خضراء صالح، مع شهادة ROA بصيغة AS13335 → 1.1.1.0/24، max-length /24 · valid."),
            notes: LocalizedText(en: "Requires internet access to reach stat.ripe.net. The result reflects the RPKI validation state as RIPEstat sees it at query time. An «unknown» status means no covering ROA exists and is not an error. Both the ASN and prefix must be supplied, and an ephemeral non-caching session ensures a fresh result.", ar: "تتطلب اتصال إنترنت للوصول إلى stat.ripe.net. النتيجة تعكس حالة التحقق من RPKI كما تراها RIPEstat لحظة الاستعلام. حالة «غير معروف» تعني غياب شهادة ROA مغطّية وليست خطأً. يجب إدخال الـ ASN والبادئة معًا، وتُستخدم جلسة عابرة بلا تخزين مؤقت لضمان نتيجة حديثة.")
        )
    ]
}
