import Foundation

extension ToolHelp {
    static let diagnosticsHelpA: [String: ToolHelpContent] = [
        "public-ip": ToolHelpContent(
            overview: LocalizedText(en: "Shows your device public IP with geo/ISP details, plus the device local interface addresses. Data loads automatically when the screen opens, and you can pull to refresh.", ar: "تعرض عنوان IP العام لجهازك مع تفاصيل الموقع الجغرافي ومزوّد الخدمة، إضافةً إلى عناوين الواجهات المحلية. تُحمَّل البيانات تلقائيًا عند فتح الشاشة، ويمكن السحب للأسفل للتحديث."),
            howItWorks: LocalizedText(en: "It sends one HTTPS request to ipwho.is with no address, so the server returns your public IP plus country, city, ISP, ASN and timezone. Local addresses are read on-device from the interfaces with no network call; HTTPS on port 443, no ICMP.", ar: "يرسل طلب HTTPS واحدًا إلى ipwho.is دون تمرير عنوان، فيعيد الخادم عنوانك العام مع الدولة والمدينة ومزوّد الخدمة وASN والمنطقة الزمنية. العناوين المحلية تُقرأ من واجهات الجهاز دون أي اتصال؛ HTTPS على المنفذ 443 بلا ICMP."),
            example: LocalizedText(en: "Open the tool → Public: 203.0.113.5, Saudi Arabia (SA), Riyadh, ISP Saudi Telecom, AS39386. Local: en0 → 192.168.1.20 (IPv4) and an fe80:: IPv6.", ar: "افتح الأداة ← العام: 203.0.113.5، السعودية (SA)، الرياض، المزوّد Saudi Telecom، AS39386. المحلي: en0 ← 192.168.1.20 (IPv4) وعنوان IPv6 يبدأ بـ fe80."),
            notes: LocalizedText(en: "Geo data is approximate from the ipwho.is database and may not be exact. Local addresses are never transmitted. Internet is required for the public section; the local section works offline.", ar: "البيانات الجغرافية تقريبية من قاعدة ipwho.is وقد لا تكون دقيقة. العناوين المحلية لا تُرسَل لأي جهة. القسم العام يتطلّب إنترنت، والقسم المحلي يعمل دون إنترنت.")
        ),
        "ip-info": ToolHelpContent(
            overview: LocalizedText(en: "Looks up geo and ISP details for any IP address or hostname you enter, not just your own. The result is an info card plus a map pinning the approximate location.", ar: "تبحث عن الموقع الجغرافي ومزوّد الخدمة لأي عنوان IP أو اسم مضيف تُدخله، لا عنوانك فقط. تظهر النتيجة كبطاقة معلومات مع خريطة تحدّد الموقع التقريبي."),
            howItWorks: LocalizedText(en: "It sends an HTTPS request to ipwho.is with your URL-encoded query; if the JSON success field is false the result is an error. On success it extracts country, city, coordinates, ISP, ASN and timezone. HTTPS on port 443; the server itself resolves any hostname.", ar: "ترسل طلب HTTPS إلى ipwho.is مع استعلامك بعد ترميزه؛ إن كان حقل success في الرد false تُعدّ النتيجة خطأً. عند النجاح تُستخرج الدولة والمدينة والإحداثيات ومزوّد الخدمة وASN والمنطقة الزمنية. HTTPS على المنفذ 443، والخادم نفسه يحلّ اسم المضيف."),
            example: LocalizedText(en: "Enter 8.8.8.8 → United States (US), ISP Google LLC, AS15169, coordinates about 37.4056, -122.0775, with a map marker.", ar: "أدخل 8.8.8.8 ← الولايات المتحدة (US)، المزوّد Google LLC، AS15169، إحداثيات نحو 37.4056، -122.0775، مع علامة على الخريطة."),
            notes: LocalizedText(en: "Geo accuracy is approximate from the ipwho.is database. The address you type is sent to ipwho.is only. Internet is required and the map is display-only.", ar: "الدقة الجغرافية تقريبية من قاعدة ipwho.is. العنوان الذي تكتبه يُرسَل إلى ipwho.is فقط. يتطلّب إنترنت، والخريطة للعرض فقط.")
        ),
        "host-to-ip": ToolHelpContent(
            overview: LocalizedText(en: "A simple tool that resolves a hostname to its IPv4 and IPv6 addresses using the iOS system resolver. It needs no special permission.", ar: "أداة بسيطة تحوّل اسم المضيف إلى عناوين IPv4 وIPv6 باستخدام مُحلِّل النظام في iOS. لا تتطلّب أي إذن خاص."),
            howItWorks: LocalizedText(en: "It calls the OS getaddrinfo with AF_UNSPEC (both families), formats each result numerically via getnameinfo and de-duplicates. No raw DNS or fixed port; the OS uses the configured DNS servers. No ICMP.", ar: "تستدعي getaddrinfo من النظام بعائلة AF_UNSPEC (IPv4 وIPv6 معًا)، وتنسّق كل نتيجة رقميًا عبر getnameinfo وتزيل التكرار. لا DNS خام ولا منفذ محدّد؛ يستخدم النظام خوادم DNS المضبوطة. لا ICMP."),
            example: LocalizedText(en: "Enter apple.com → shows an IPv4 like 17.253.144.10 plus IPv6 addresses if available. A nonexistent name shows not found.", ar: "أدخل apple.com ← يعرض عنوان IPv4 مثل 17.253.144.10 وعناوين IPv6 إن توفّرت. اسم غير موجود يعرض غير موجود."),
            notes: LocalizedText(en: "Results depend on the device DNS config and can vary by network. No Local Network permission is needed since this is public DNS. Results reflect the first set the system returns and may not include every address.", ar: "النتائج تعتمد على إعدادات DNS للجهاز وقد تختلف حسب الشبكة. لا يلزم إذن الشبكة المحلية لأنه حلّ DNS عام. تعكس النتائج أول مجموعة يعيدها النظام وقد لا تشمل كل العناوين.")
        ),
        "nslookup": ToolHelpContent(
            overview: LocalizedText(en: "Resolves a domain name to IP addresses (forward), or an IPv4 address to its hostname (reverse/PTR). It auto-detects the input type and uses the system resolver.", ar: "تحوّل اسم النطاق إلى عناوين IP (بحث أمامي)، أو عنوان IPv4 إلى اسم مضيفه (بحث عكسي/PTR). تكتشف نوع المدخل تلقائيًا وتعتمد على مُحلِّل النظام."),
            howItWorks: LocalizedText(en: "For an IPv4 input it runs reverse mode via getnameinfo with NI_NAMEREQD for the PTR record. Otherwise forward mode uses getaddrinfo (AF_UNSPEC) to gather all addresses. Both use the OS DNS resolver over POSIX APIs on a background thread.", ar: "إذا كان المدخل IPv4 يعمل بالوضع العكسي عبر getnameinfo مع الراية NI_NAMEREQD للحصول على سجل PTR. وإلا فالوضع الأمامي يستخدم getaddrinfo بعائلة AF_UNSPEC لجمع كل العناوين. كلاهما يستخدم مُحلِّل النظام عبر واجهات POSIX على خيط خلفي."),
            example: LocalizedText(en: "dns.google (forward) returns 8.8.8.8, 8.8.4.4 and IPv6 addresses. 8.8.8.8 (reverse) returns the hostname dns.google.", ar: "المدخل dns.google (أمامي) يعيد 8.8.8.8 و8.8.4.4 وعناوين IPv6. المدخل 8.8.8.8 (عكسي) يعيد اسم المضيف dns.google."),
            notes: LocalizedText(en: "Reverse lookup supports IPv4 only and needs the host to have a PTR record. Results are subject to the system resolver cache. No special iOS permissions are required.", ar: "البحث العكسي يدعم IPv4 فقط ويتطلّب وجود سجل PTR للمضيف. النتائج تخضع لتخزين مُحلِّل النظام المؤقت. لا يتطلّب أذونات خاصة على iOS.")
        ),
        "ping": ToolHelpContent(
            overview: LocalizedText(en: "Measures reachability and latency to a host. It sends real ICMP/ICMPv6 echoes and automatically switches to a TCP-handshake measurement when ICMP is filtered. Options: count, period, timeout, payload size and TTL.", ar: "يقيس قابلية الوصول وزمن الاستجابة لمضيف. يرسل صدى ICMP/ICMPv6 حقيقيًا ويتحوّل تلقائيًا إلى قياس مصافحة TCP عند حجب ICMP. خيارات: العدد والفترة والمهلة وحجم الحمولة وTTL."),
            howItWorks: LocalizedText(en: "It resolves the host then sends ICMP echoes over the unprivileged datagram socket (like Apple SimplePing); IPv4 uses IPPROTO_ICMP and IPv6 uses IPPROTO_ICMPV6. TCP fallback: if the first echo is unanswered, the run switches to timing a TCP handshake to a fallback port (default 443).", ar: "يحلّ المضيف ثم يرسل صدى ICMP عبر مقبس البيانات غير المميّز (كما تفعل SimplePing من Apple)؛ IPv4 يستخدم IPPROTO_ICMP وIPv6 يستخدم IPPROTO_ICMPV6. التحوّل إلى TCP: إن لم يُرَدّ أول صدى، يتحوّل التشغيل لقياس زمن مصافحة TCP إلى منفذ احتياطي (افتراضيًا 443)."),
            example: LocalizedText(en: "Enter 1.1.1.1, count 5 → avg 12 ms, min 10/max 15, 0 percent loss. On an ICMP-filtering network a TCP mode notice appears and the handshake time to port 443 is measured instead.", ar: "أدخل 1.1.1.1 بعدد 5 ← متوسط 12 ms، أدنى 10/أقصى 15، فقد 0 بالمئة. على شبكة تحجب ICMP يظهر تنبيه وضع TCP ويُقاس زمن المصافحة إلى المنفذ 443 بدلًا من ذلك."),
            notes: LocalizedText(en: "On iOS raw ICMP sockets are unavailable, so it uses the unprivileged ICMP datagram socket; if ICMP is fully blocked the result reflects a TCP handshake time. Measurements depend on momentary network conditions. Nothing is sent to any third party.", ar: "على iOS لا تتوفّر مقابس ICMP الخام، فتستخدم الأداة مقبس ICMP بالبيانات غير المميّز؛ وإن حُجب ICMP كليًا فالنتيجة تعكس زمن مصافحة TCP. القياسات تعتمد على حالة الشبكة اللحظية. لا يُرسَل شيء لأي طرف ثالث.")
        ),
        "traceroute": ToolHelpContent(
            overview: LocalizedText(en: "Traces the network path (hops) to a host, showing each router and its round-trip time; non-replying routers show as an asterisk. If ICMP is fully blocked, a TCP probe confirms reachability and hop distance instead.", ar: "يتتبّع مسار الشبكة (القفزات) إلى مضيف، مُظهرًا كل موجّه وزمن استجابته؛ الموجّهات التي لا تردّ تظهر كنجمة. وإن حُجب ICMP كليًا يستخدم فحص TCP لتأكيد الوصول ومسافة القفزات بدلًا من ذلك."),
            howItWorks: LocalizedText(en: "It uses the unprivileged ICMP datagram socket, sending echoes with increasing TTL; intermediate routers reply Time Exceeded and the destination replies Echo Reply. It probes all TTLs at once via a TaskGroup. TCP fallback: if ICMP yields no usable address, a TCP reachability probe gives hop distance and RTT.", ar: "تستخدم مقبس ICMP بالبيانات غير المميّز، وترسل صدى بقيمة TTL متزايدة؛ الموجّهات الوسيطة تردّ Time Exceeded والهدف يردّ Echo Reply. تفحص كل قيم TTL دفعةً واحدة عبر TaskGroup. التحوّل إلى TCP: إن لم يُنتج ICMP عنوانًا مفيدًا، يعطي فحص وصول TCP مسافة القفزات وزمن RTT."),
            example: LocalizedText(en: "Enter 8.8.8.8 → hops like 1 192.168.1.1 1.2 ms, 2 asterisk, 3 10.x.x.x 8.4 ms, ending at dns.google with a reached badge. On an ICMP-filtering network a reachable via TCP :443 card shows about 8 hops and 42 ms.", ar: "أدخل 8.8.8.8 ← قفزات مثل 1 192.168.1.1 1.2 ms، 2 نجمة، 3 10.x.x.x 8.4 ms، حتى dns.google بشارة تم الوصول. على شبكة تحجب ICMP تظهر بطاقة وصول عبر TCP :443 بنحو 8 قفزات و42 ms."),
            notes: LocalizedText(en: "On iOS raw ICMP sockets are unavailable; if it is fully blocked the result is a TCP reachability probe rather than a full ICMP path. Silent hops may mean routers that do not reply, not an outage. Only probe targets you are authorized to test.", ar: "على iOS لا تتوفّر مقابس ICMP الخام؛ وإن حُجبت كليًا فالنتيجة فحص وصول TCP لا مسار ICMP كامل. القفزات الصامتة قد تعني موجّهات لا تردّ لا انقطاعًا. افحص فقط أهدافًا مصرّحًا لك بها.")
        ),
        "mtr": ToolHelpContent(
            overview: LocalizedText(en: "A continuous traceroute combining per-hop packet loss and latency across repeated rounds. Each hop shows last/avg/best/worst latency, loss, and the router origin AS, clarifying where along the path a problem lies.", ar: "تتبّع مسار متواصل يجمع فقد الحزم وزمن الاستجابة لكل قفزة عبر جولات متكرّرة. كل قفزة تعرض آخر/متوسط/أفضل/أسوأ زمن ونسبة الفقد ورقم AS للموجّه، ما يوضّح موضع المشكلة على الطريق."),
            howItWorks: LocalizedText(en: "It uses the same unprivileged ICMP datagram tracer, probing all TTLs each round and folding results into running per-hop stats, repeating every second until stopped. AS enrichment (optional) reverses each hop IPv4 and queries a TXT record at origin.asn.cymru.com via raw DNS UDP 53 to server 1.1.1.1 (Team Cymru).", ar: "تستخدم مُحرّك التتبّع نفسه بمقبس ICMP بالبيانات غير المميّز، وتفحص كل قيم TTL في كل جولة وتُجمّع النتائج في إحصاءات جارية لكل قفزة، مكرّرةً كل ثانية حتى الإيقاف. إثراء AS (اختياري) يعكس IPv4 لكل قفزة ويستعلم عن سجل TXT في origin.asn.cymru.com عبر DNS خام UDP على المنفذ 53 إلى الخادم 1.1.1.1 (Team Cymru)."),
            example: LocalizedText(en: "Enter apple.com with ASN lookup on → hop 1 192.168.1.1 loss 0 percent avg 2 ms; hop 5 AS3356 loss 0 percent avg 14 ms; up to the destination marked reached. The rounds count grows and CSV can be exported.", ar: "أدخل apple.com مع تفعيل بحث AS ← القفزة 1 192.168.1.1 فقد 0 بالمئة متوسط 2 ms؛ القفزة 5 AS3356 فقد 0 بالمئة متوسط 14 ms؛ حتى الهدف بعلامة تم الوصول. يتراكم عدد الجولات ويمكن تصدير CSV."),
            notes: LocalizedText(en: "Raw ICMP sockets are unavailable on iOS; some hops may not appear if the network filters ICMP, and unlike Traceroute there is no explicit TCP fallback here. AS lookup depends on Team Cymru via DNS to 1.1.1.1. The run is continuous and uses battery and data until you stop it.", ar: "مقابس ICMP الخام غير متوفّرة على iOS؛ قد لا تظهر بعض القفزات إن حجبت الشبكة ICMP، وبخلاف Traceroute لا يوجد هنا تحوّل صريح إلى TCP. استعلام AS يعتمد على Team Cymru عبر DNS إلى 1.1.1.1. التشغيل متواصل ويستهلك بطارية وبيانات حتى تُوقفه.")
        ),
        "world-ping": ToolHelpContent(
            overview: LocalizedText(en: "Measures reachability to a target from probe locations distributed around the globe, not from your device. Each row shows the probe location, network, latency (min/avg/max) and loss, useful to see how your server appears from different continents.", ar: "يقيس الوصول إلى هدف من مسابير موزّعة حول العالم، لا من جهازك. كل صف يعرض موقع المِسبار وشبكته وزمن الاستجابة (أدنى/متوسط/أقصى) ونسبة الفقد، لمعرفة كيف يُرى خادمك من قارات مختلفة."),
            howItWorks: LocalizedText(en: "It uses the free key-less globalping.io network via api.globalping.io over HTTPS on port 443: a POST starts a ping measurement and returns an id, then it polls that id every second (up to 25 times) until finished. The remote probes do the actual pinging, so there is no local ICMP on your device.", ar: "تستخدم شبكة globalping.io المجانية بلا مفتاح عبر api.globalping.io على HTTPS منفذ 443: طلب POST يبدأ قياس ping ويعيد معرّفًا، ثم تستطلعه كل ثانية (حتى 25 مرة) حتى ينتهي. المسابير البعيدة تنفّذ البينغ الفعلي، فلا ICMP محلي على جهازك."),
            example: LocalizedText(en: "Target 1.1.1.1, limit 8 → London 2/3 · 0 percent · 1/3/4 ms, Tokyo about 2 ms, Sao Paulo about 4 ms, and so on for other probes.", ar: "الهدف 1.1.1.1 بحدّ 8 ← London‏ 2/3 · 0 بالمئة · 1/3/4 ms، Tokyo نحو 2 ms، Sao Paulo نحو 4 ms، وهكذا لمسابير أخرى."),
            notes: LocalizedText(en: "It depends entirely on the public globalping.io network and may be slow or fail when busy. The target you type is sent to api.globalping.io. Internet is required. Polling is capped at 25 attempts (about 25 seconds).", ar: "تعتمد كليًا على شبكة globalping.io العامة وقد تتأخّر أو تفشل عند انشغالها. الهدف الذي تكتبه يُرسَل إلى api.globalping.io. يتطلّب إنترنت. الاستطلاع محدود بـ 25 محاولة (نحو 25 ثانية).")
        ),
        "port-scanner": ToolHelpContent(
            overview: LocalizedText(en: "A fully local tool that scans TCP ports on a host to see which are open, by attempting a real TCP handshake to each port via the iOS Network framework. No data is sent to any external service.", ar: "أداة محلية بالكامل تفحص منافذ TCP على مضيف لمعرفة المفتوح منها، عبر محاولة مصافحة TCP حقيقية لكل منفذ باستخدام إطار Network في iOS. لا تُرسَل أي بيانات لأي خدمة خارجية."),
            howItWorks: LocalizedText(en: "For each port it opens an NWConnection of type tcp; reaching ready means open, while failed or waiting means closed. Scanning runs with bounded concurrency (up to 24 ports at once) with a 1.5 second timeout per port. Service names come from a local database. No UDP scan and no raw packets.", ar: "لكل منفذ تفتح اتصال NWConnection من نوع tcp؛ بلوغ الحالة ready يعني مفتوح، وfailed أو waiting يعني مغلق. يجري الفحص بتوازٍ محدود (حتى 24 منفذًا في آن) بمهلة 1.5 ثانية لكل منفذ. أسماء الخدمات من قاعدة محلية. لا فحص UDP ولا حِزم خام."),
            example: LocalizedText(en: "Enter host scanme.nmap.org with preset common. Typical result: 22 ssh and 80 http shown as open, the rest closed, with a 2 open badge.", ar: "أدخل المضيف scanme.nmap.org مع النمط common. النتيجة النموذجية: 22 ssh و80 http مفتوحان والبقية مغلقة، مع شارة 2 open."),
            notes: LocalizedText(en: "This is TCP-connect scanning only (no stealth SYN, no UDP), so it is visible in the target logs. A port may read closed due to filtering rather than an absent service. Everything runs locally; only scan systems you are authorized to test.", ar: "هذا فحص TCP-connect فقط (لا SYN خفي ولا UDP)، لذا يظهر في سجلّات الهدف. قد يظهر منفذ مغلق بسبب الحجب لا لغياب الخدمة. كل شيء محلي؛ افحص فقط أنظمة مصرّحًا لك بها.")
        ),
        "banner-grab": ToolHelpContent(
            overview: LocalizedText(en: "A local tool that connects to a TCP port and reads what the service announces on connect (SSH/FTP/SMTP banners), or its reply to an optional probe line such as an HTTP request. It helps identify the service and version behind a port.", ar: "أداة محلية تتصل بمنفذ TCP وتقرأ ما تعلنه الخدمة عند الاتصال (لافتات SSH/FTP/SMTP)، أو ردّها على سطر تحقيق اختياري مثل طلب HTTP. تساعد في تحديد نوع الخدمة وإصدارها خلف منفذ."),
            howItWorks: LocalizedText(en: "It opens a TCPConnection to the host and port with a 5-second timeout (optional TLS). A non-empty probe line is sent followed by CRLF CRLF, then it reads everything the service returns and shows it as text. The connection is direct from device to target; with TLS on it fits ports like 443, 465 or 993.", ar: "تفتح اتصال TCPConnection نحو المضيف والمنفذ بمهلة 5 ثوانٍ (مع TLS اختياري). سطر التحقيق غير الفارغ يُرسَل متبوعًا بمحرفَي سطر جديد، ثم تقرأ كل ما ترجعه الخدمة وتعرضه نصًّا. الاتصال مباشر من الجهاز إلى الهدف؛ ومع TLS يناسب منافذ مثل 443 و465 و993."),
            example: LocalizedText(en: "Host github.com, port 22, no probe → an SSH banner like SSH-2.0-babeld. Or host example.com, port 80 with probe GET / HTTP/1.0 returns HTTP response headers.", ar: "المضيف github.com والمنفذ 22 بلا تحقيق ← لافتة SSH مثل SSH-2.0-babeld. أو المضيف example.com والمنفذ 80 مع تحقيق GET / HTTP/1.0 يعيد ترويسات استجابة HTTP."),
            notes: LocalizedText(en: "Services that do not auto-announce a banner (many HTTP servers) need a probe line to reply. The 5-second timeout is fixed and outbound TCP to the port must be allowed. Everything is local, but the connection is visible in the target logs; use only on authorized systems.", ar: "الخدمات التي لا تعلن لافتة تلقائيًا (كثير من خوادم HTTP) تحتاج سطر تحقيق للرد. مهلة 5 ثوانٍ ثابتة ويلزم سماح الشبكة باتصال TCP الخارج للمنفذ. كل شيء محلي، لكن الاتصال مرئي في سجلّات الهدف؛ استخدمه فقط على أنظمة مصرّح لك بها.")
        ),
        "fingerprint": ToolHelpContent(
            overview: LocalizedText(en: "Opens a direct TCP connection to the host and port you specify, reads the banner the service announces, then heuristically infers the service type and product by pattern-matching. All identification runs locally on the device.", ar: "تفتح اتصال TCP مباشرًا بالمضيف والمنفذ اللذين تحدّدهما، وتقرأ اللافتة التي تعلنها الخدمة، ثم تستنتج نوع الخدمة والمنتج بمطابقة أنماط. كل الاستدلال يجري محليًا على الجهاز."),
            howItWorks: LocalizedText(en: "It connects via TCPConnection (6-second timeout); for common HTTP ports (80, 443, 8000, 8008, 8080, 8443) it sends a GET / HTTP/1.0 probe, otherwise it reads the auto-announced banner. Ports 443 and 8443 use TLS. Heuristics classify SSH, HTTP (Server header), FTP, SMTP, IMAP, POP3, Redis and MySQL, falling back to the port well-known name.", ar: "تتصل عبر TCPConnection (مهلة 6 ثوانٍ)؛ لمنافذ HTTP الشائعة (80 و443 و8000 و8008 و8080 و8443) ترسل مسبار GET / HTTP/1.0، وإلا تقرأ اللافتة المُعلَنة تلقائيًا. المنفذان 443 و8443 يستخدمان TLS. قواعد استدلالية تصنّف SSH وHTTP (ترويسة Server) وFTP وSMTP وIMAP وPOP3 وRedis وMySQL، وعند عدم التطابق تعود لاسم المنفذ المعروف."),
            example: LocalizedText(en: "Input example.com with port 22: it reads the banner SSH-2.0-OpenSSH_8.9p1 Ubuntu-3 and reports service SSH, product OpenSSH_8.9p1 Ubuntu-3.", ar: "المدخل example.com مع المنفذ 22: تقرأ اللافتة SSH-2.0-OpenSSH_8.9p1 Ubuntu-3، فتعرض الخدمة SSH والمنتج OpenSSH_8.9p1 Ubuntu-3."),
            notes: LocalizedText(en: "Identification is heuristic and depends on what the service exposes; services that suppress banners may be labeled unknown. The connection is direct from your device to the target, so only probe authorized systems. No special iOS permissions, but firewalls may block uncommon ports.", ar: "الاستدلال تقريبي ويعتمد على ما تكشفه الخدمة؛ الخدمات التي تُخفي اللافتة قد تُصنَّف unknown. الاتصال مباشر من جهازك إلى الهدف، فافحص فقط أنظمة مصرّحًا لك بها. لا أذونات خاصة على iOS، لكن جدران الحماية قد تحجب المنافذ غير الشائعة.")
        ),
        "dns-lookup": ToolHelpContent(
            overview: LocalizedText(en: "Sends a raw DNS query directly to a name server of your choice over UDP on port 53 and decodes the answer itself, using the app in-house DNSMessage codec instead of the system resolver.", ar: "ترسل استعلام DNS خامًا مباشرةً إلى خادم أسماء تختاره عبر UDP على المنفذ 53 وتفكّ الإجابة بنفسها، مستخدمةً مُرمِّز DNSMessage داخل التطبيق بدل مُحلِّل النظام."),
            howItWorks: LocalizedText(en: "DNSMessage.encodeQuery builds a wire-format packet (fixed ID) sent via a short-lived UDP socket to host:53 with a 5-second timeout, and DNSMessage.decodeAnswers parses the reply into records. This is direct UDP to port 53 on the entered server, not DoH and not the OS resolver.", ar: "يبني DNSMessage.encodeQuery حزمة بصيغة wire-format (بمعرّف ثابت) تُرسَل عبر مقبس UDP قصير العمر إلى host:53 بمهلة 5 ثوانٍ، ويفكّ DNSMessage.decodeAnswers الرد إلى سجلات. هذا UDP مباشر للمنفذ 53 على الخادم المُدخَل، لا DoH ولا مُحلِّل النظام."),
            example: LocalizedText(en: "Name example.com, type A, server 1.1.1.1 → an A record with a value like 93.184.215.14 and TTL 3600s.", ar: "الاسم example.com والنوع A والخادم 1.1.1.1 ← سجل A بقيمة مثل 93.184.215.14 وTTL‏ 3600s."),
            notes: LocalizedText(en: "Requires the network to allow UDP on port 53 to a custom server; some networks block outbound DNS. The query is unencrypted and observable on the network (use the DoH tool for encryption). Each query uses its own short-lived socket.", ar: "يتطلّب سماح الشبكة بحركة UDP على المنفذ 53 إلى خادم مخصّص؛ بعض الشبكات تحجب DNS الخارج. الاستعلام غير مشفّر ويمكن مراقبته على الشبكة (استخدم أداة DoH للتشفير). كل استعلام يستخدم مقبسًا مستقلًا قصير العمر.")
        ),
        "doh": ToolHelpContent(
            overview: LocalizedText(en: "Performs an encrypted DNS query over HTTPS per RFC 8484: it sends a wire-format query inside an encrypted POST to a public DoH resolver and decodes the reply with the same DNSMessage codec, preventing on-path snooping or tampering.", ar: "تنفّذ استعلام DNS مشفّرًا عبر HTTPS وفق RFC 8484: ترسل استعلامًا بصيغة wire-format داخل طلب POST مشفّر إلى مُحلِّل DoH عام وتفكّ الرد بمُرمِّز DNSMessage نفسه، ما يمنع التنصّت أو التلاعب على الشبكة."),
            howItWorks: LocalizedText(en: "The query is POSTed to https://server/dns-query with content-type and accept set to application/dns-message, a 10-second timeout over an ephemeral URLSession; effective port is 443. The default server is cloudflare-dns.com, and dns.google or dns.quad9.net also work.", ar: "يُرسَل الاستعلام بطلب POST إلى https://server/dns-query مع الترويستين content-type وaccept بقيمة application/dns-message، بمهلة 10 ثوانٍ عبر URLSession مؤقتة؛ المنفذ الفعلي 443. الخادم الافتراضي cloudflare-dns.com، ويعمل أيضًا dns.google أو dns.quad9.net."),
            example: LocalizedText(en: "Name cloudflare.com, type AAAA, server cloudflare-dns.com → AAAA records with IPv6 values like 2606:4700::6810:85e5.", ar: "الاسم cloudflare.com والنوع AAAA والخادم cloudflare-dns.com ← سجلات AAAA بقيم IPv6 مثل 2606:4700::6810:85e5."),
            notes: LocalizedText(en: "Requires internet; an outage surfaces an offline state. The query passes through an external resolver (Cloudflare/Google/Quad9) that sees the name even though transport is encrypted. Port 443 is rarely blocked, making DoH a practical fallback when classic DNS on port 53 is filtered.", ar: "يتطلّب إنترنت؛ وعند الانقطاع تظهر حالة offline. يمرّ الاستعلام عبر مُحلِّل خارجي (Cloudflare/Google/Quad9) يرى الاسم رغم تشفير النقل. المنفذ 443 نادرًا ما يُحجَب، ما يجعل DoH بديلاً عمليًا حين يُحجَب DNS التقليدي على المنفذ 53.")
        ),
        "dns-compare": ToolHelpContent(
            overview: LocalizedText(en: "Queries the same record from several public DNS-over-HTTPS resolvers at once and compares their answers, revealing propagation lag or divergent responses (filtering, poisoning, geo-blocking) across providers.", ar: "تستعلم عن نفس السجل من عدة مُحلِّلات DNS-over-HTTPS عامة في آنٍ واحد وتقارن إجاباتها، فتكشف تأخّر الانتشار أو الإجابات المتباينة (تصفية أو تسميم أو حجب جغرافي) بين المزوّدين."),
            howItWorks: LocalizedText(en: "It runs an encrypted RFC 8484 POST to /dns-query on port 443 in parallel against four fixed resolvers: Cloudflare (cloudflare-dns.com), Google (dns.google), Quad9 (dns.quad9.net) and AdGuard (dns.adguard-dns.com). Results are filtered to the type and sorted, then an agreement flag compares the value sets of resolvers that answered.", ar: "تنفّذ استعلامًا مشفّرًا وفق RFC 8484 بطلب POST إلى ‎/dns-query على المنفذ 443 بالتوازي لأربعة مُحلِّلات ثابتة: Cloudflare‏ (cloudflare-dns.com) وGoogle‏ (dns.google) وQuad9‏ (dns.quad9.net) وAdGuard‏ (dns.adguard-dns.com). تُرشَّح النتائج حسب النوع وتُرتَّب، ثم تقارن شارة الاتفاق مجموعات قيم المُحلِّلات التي أجابت."),
            example: LocalizedText(en: "Name github.com, type A: Cloudflare, Google, Quad9 and AdGuard all show the same address (e.g. 140.82.121.4) with an agree badge. For an ad-filtered domain AdGuard may return 0.0.0.0, producing disagree.", ar: "الاسم github.com والنوع A: تُظهر Cloudflare وGoogle وQuad9 وAdGuard نفس العنوان (مثل 140.82.121.4) مع شارة agree. أما نطاق مُصفّى إعلانيًا فقد تعيد AdGuard القيمة 0.0.0.0 فتظهر شارة disagree."),
            notes: LocalizedText(en: "Requires internet and four parallel HTTPS queries. A disagreement is not necessarily a fault; it can come from geographic load balancing (CDN) or intentional filtering by a resolver. The resolver list is fixed to these four and not user-customizable.", ar: "تتطلّب إنترنت وأربعة استعلامات HTTPS متوازية. الاختلاف ليس بالضرورة خللًا؛ فقد ينتج عن توازن الأحمال الجغرافي (CDN) أو تصفية متعمّدة لدى مُحلِّل. قائمة المُحلِّلات ثابتة على الأربعة ولا تُخصَّص من الواجهة.")
        ),
        "dns-reliability": ToolHelpContent(
            overview: LocalizedText(en: "A continuous monitor that repeats a single DNS query at regular intervals and measures response time and success rate over time, useful for spotting jitter and intermittent drops. It works over UDP directly to the server on port 53.", ar: "مراقب مستمر يُكرّر استعلام DNS واحدًا على فترات منتظمة ويقيس زمن الاستجابة ومعدّل النجاح مع الوقت، مفيد لرصد التذبذب والانقطاعات المتقطّعة. يعمل عبر UDP مباشرةً إلى الخادم على المنفذ 53."),
            howItWorks: LocalizedText(en: "In a loop it sends a wire-format query via UDP to server:53 (5-second timeout), timing each round-trip in milliseconds and recording success or drop. A pure engine computes running stats: success rate, min/avg/max latency, jitter, drop episodes, longest drop streak, and slow responses over the threshold. It keeps at most the last 200 samples.", ar: "في حلقة متواصلة ترسل استعلامًا بصيغة wire-format عبر UDP إلى server:53 (مهلة 5 ثوانٍ)، وتقيس كل رحلة بالملّي ثانية وتسجّل نجاحًا أو إسقاطًا. يحسب محرّك نقيّ إحصاءات جارية: معدّل النجاح وأدنى/متوسط/أعلى زمن والتذبذب ونوبات الإسقاط وأطول سلسلة إسقاط والردود البطيئة فوق العتبة. يحتفظ بآخر 200 عيّنة كحد أقصى."),
            example: LocalizedText(en: "Host apple.com, server 8.8.8.8, interval 1.0, threshold 200. After 60 samples: success rate 100 percent, latency range 18 to 45 ms, average 27 ms, jitter 6 ms, zero drop episodes, status stable.", ar: "المضيف apple.com والخادم 8.8.8.8 والفاصل 1.0 والعتبة 200. بعد 60 عيّنة: معدّل نجاح 100 بالمئة، نطاق زمن 18 إلى 45 ms، متوسط 27 ms، تذبذب 6 ms، صفر نوبات إسقاط، وحالة stable."),
            notes: LocalizedText(en: "Monitoring runs while the tool is active and consumes continuous traffic and battery; the 200-sample cap discards the oldest. Requires the network to permit UDP on port 53. Latencies include the full round-trip and can be affected by device load. The session persists across in-app navigation until you stop it.", ar: "تعمل المراقبة طالما الأداة نشطة وتستهلك حركة مستمرة وبطارية؛ وحد 200 عيّنة يُسقط الأقدم. تتطلّب سماح الشبكة بحركة UDP على المنفذ 53. الأزمنة تشمل الرحلة الكاملة وقد تتأثّر بحمل الجهاز. تبقى الجلسة قائمة عبر التنقّل حتى تُوقفها يدويًا.")
        ),
        "dns-health": ToolHelpContent(
            overview: LocalizedText(en: "Checks a domain health from two angles: propagation consistency across several public resolvers, and DNSSEC signing status. It queries the same record from six well-known resolvers over UDP and compares answers, then verifies the security signature.", ar: "تفحص صحّة نطاق من زاويتين: اتساق الانتشار عبر عدة مُحلِّلات عامة، وحالة توقيع DNSSEC. تستعلم عن نفس السجل من ستة مُحلِّلات مشهورة عبر UDP وتقارن الإجابات، ثم تتحقّق من التوقيع الأمني."),
            howItWorks: LocalizedText(en: "Propagation: parallel UDP queries on port 53 from six fixed resolvers (Cloudflare 1.1.1.1, Google 8.8.8.8, Quad9 9.9.9.9, OpenDNS 208.67.222.222, AdGuard 94.140.14.14, Level3 4.2.2.2); consistent if every answering resolver returns the same values. DNSSEC: a query with the EDNS0 DO bit to 1.1.1.1:53, reading the response flags where the AD bit means signed, its absence unsigned, rcode 2 bogus, and no reply unknown.", ar: "الانتشار: استعلامات UDP متوازية على المنفذ 53 من ستة مُحلِّلات ثابتة (Cloudflare‏ 1.1.1.1، Google‏ 8.8.8.8، Quad9‏ 9.9.9.9، OpenDNS‏ 208.67.222.222، AdGuard‏ 94.140.14.14، Level3‏ 4.2.2.2)؛ يُعدّ متّسقًا إن أعادت كل المُحلِّلات المجيبة القيم نفسها. DNSSEC: استعلام ببِت EDNS0 DO إلى 1.1.1.1:53، وقراءة أعلام الرد حيث بِت AD يعني signed وغيابه unsigned وrcode‏ 2 يعني bogus وتعذّر الرد unknown."),
            example: LocalizedText(en: "Host cloudflare.com, type A → DNSSEC signed and propagation consistent with all six resolvers showing the same addresses. A domain without signing shows unsigned.", ar: "المضيف cloudflare.com والنوع A ← DNSSEC‏ signed والانتشار consistent مع إظهار المُحلِّلات الستة نفس العناوين. أما نطاق بلا توقيع فيظهر unsigned."),
            notes: LocalizedText(en: "The DNSSEC check relies on a single validating resolver (1.1.1.1) and the AD bit; it is indirect and does not validate the chain locally. Consistency can be affected by geographic load balancing (CDN), showing inconsistent even for a healthy domain. Requires UDP on port 53 to all six resolvers.", ar: "يعتمد فحص DNSSEC على مُحلِّل مُتحقِّق واحد (1.1.1.1) وبِت AD؛ فهو غير مباشر ولا يتحقّق من السلسلة محليًا. قد يتأثّر الاتساق بتوازن الأحمال الجغرافي (CDN) فيظهر inconsistent رغم سلامة النطاق. يتطلّب حركة UDP على المنفذ 53 لكل المُحلِّلات الستة.")
        ),
        "http-request": ToolHelpContent(
            overview: LocalizedText(en: "A mini HTTP client that sends a custom request with your chosen method, URL, headers and body, then shows the response status code, headers and body. Handy for quickly testing REST APIs from the device.", ar: "عميل HTTP مصغّر يرسل طلبًا مخصّصًا باختيار الطريقة والرابط والترويسات والجسم، ثم يعرض رمز الحالة والترويسات والجسم في الرد. مفيد لاختبار واجهات REST سريعًا من الجهاز."),
            howItWorks: LocalizedText(en: "It builds a URLRequest via an ephemeral URLSession over the URL protocol and port (typically HTTPS 443 or HTTP 80); https:// is prepended if missing. It sets a 20-second timeout and a NetToolbox/1.0 User-Agent, parses headers line by line, and sends a body only for non-GET/HEAD methods. The displayed body is truncated to 20,000 characters; the request goes straight to the server.", ar: "يبني URLRequest عبر URLSession مؤقتة على بروتوكول ومنفذ الرابط (عادةً HTTPS‏ 443 أو HTTP‏ 80)؛ ويُضاف https:// إن غاب. يضبط مهلة 20 ثانية وترويسة User-Agent بقيمة NetToolbox/1.0، ويحلّل الترويسات سطرًا بسطر، ويرسل الجسم فقط للطرق غير GET/HEAD. الجسم المعروض يُقتطَع إلى 20000 حرف؛ ويذهب الطلب مباشرةً إلى الخادم."),
            example: LocalizedText(en: "GET https://api.github.com → status 200 with a JSON body of endpoint links. POST to https://httpbin.org/post with body a:1 and header Content-Type application/json → 200 echoing the sent data.", ar: "GET‏ https://api.github.com ← الحالة 200 وجسم JSON بروابط الواجهة. وPOST إلى https://httpbin.org/post بجسم a:1 وترويسة Content-Type‏ application/json ← 200 مع صدى للبيانات المُرسَلة."),
            notes: LocalizedText(en: "The displayed body is capped at 20,000 characters and the timeout is 20 seconds. If the internet is down an offline message appears. Neither request nor response is stored. Data goes directly to the target server; only send requests to servers you are authorized to test.", ar: "الجسم المعروض محدود بـ 20000 حرف والمهلة 20 ثانية. عند انقطاع الإنترنت تظهر رسالة غير متصل. لا يُخزَّن الطلب ولا الرد. البيانات تذهب مباشرةً للخادم الهدف؛ أرسل الطلبات فقط لخوادم مصرّح لك باختبارها.")
        ),
        "http-headers": ToolHelpContent(
            overview: LocalizedText(en: "Fetches a URL and displays the status line and all response headers, sorted alphabetically. Useful for inspecting security headers, caching, content type and the server. It runs locally via the system network stack.", ar: "تجلب عنوانًا وتعرض سطر الحالة وكل ترويسات الاستجابة مرتّبةً أبجديًا. مفيدة لفحص ترويسات الأمان والتخزين المؤقت ونوع المحتوى والخادم. تعمل محليًا عبر مكدّس شبكة النظام."),
            howItWorks: LocalizedText(en: "If the scheme is missing it prepends https://, then issues a GET via an ephemeral URLSession with a 15-second timeout and a NetToolbox/1.0 User-Agent. From the HTTPURLResponse it reads the status code, the final URL after redirects, and all headers converted to name/value pairs sorted by name. An unreachable network returns an offline error.", ar: "إن غاب البروتوكول تضيف https://، ثم ترسل طلب GET عبر URLSession مؤقتة بمهلة 15 ثانية وترويسة User-Agent بقيمة NetToolbox/1.0. من HTTPURLResponse تقرأ رمز الحالة والعنوان النهائي بعد إعادة التوجيه وكل الترويسات كأزواج اسم/قيمة مرتّبة بالاسم. تعذّر الشبكة يُرجِع خطأ offline."),
            example: LocalizedText(en: "Input github.com → status 200, final URL https://github.com/, and headers such as content-type text/html; charset=utf-8, server GitHub.com, strict-transport-security max-age=31536000.", ar: "المدخل github.com ← الحالة 200، العنوان النهائي https://github.com/، وترويسات مثل content-type‏ text/html; charset=utf-8، وserver‏ GitHub.com، وstrict-transport-security‏ max-age=31536000."),
            notes: LocalizedText(en: "It follows redirects automatically, so it shows only the final response headers. Some servers respond differently to GET versus HEAD. The ephemeral session carries no cookies or cache. No special iOS permissions are required.", ar: "تتبع إعادة التوجيه تلقائيًا فتعرض ترويسات الاستجابة النهائية فقط. بعض الخوادم تختلف استجابتها لطلب GET عن HEAD. الجلسة المؤقتة بلا كوكيز أو تخزين مؤقت. لا تتطلّب أذونات خاصة على iOS.")
        ),
    ]
}
